# Generated by Django 5.1.3 on 2024-11-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        
    ]
