# Generated by Django 5.1.3 on 2024-11-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_item_item_category_delete_category'),
    ]

    operations = [
    ]
