# Generated by Django 5.1.3 on 2024-11-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_item_category_item_category'),
    ]

    operations = [
    ]
