# Generated by Django 5.1.3 on 2024-11-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_category_item_item_category'),
    ]

    operations = [
    ]
