# Generated by Django 5.1.3 on 2024-11-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_item_item_category'),
    ]

    operations = [
    ]
