# Generated by Django 5.1.3 on 2024-11-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_delete_category'),
    ]

    operations = [
    ]
