# Generated by Django 5.1.3 on 2024-11-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_remove_item_item_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
