# Generated by Django 5.1.3 on 2024-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_item_item_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Item Category'),
        ),
    ]
