# Generated by Django 5.1.3 on 2024-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(max_length=100, verbose_name='Item Category'),
        ),
    ]
